# Create playbook.yml
cat <<EOF > playbook.yml
---
- name: Create devops user with SSH access and sudo privileges
  hosts: servers
  become: true

  vars:
    username: devops
    ssh_pub_key: "{{ lookup('file', 'files/devops.pub') }}"

  tasks:
    - name: Create user "{{ username }}"
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes
        password: "*"
        state: present

    - name: Create .ssh directory for the user
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add SSH public key to authorized_keys
      ansible.builtin.copy:
        content: "{{ ssh_pub_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Disable password login for the user
      ansible.builtin.user:
        name: "{{ username }}"
        password_lock: true
EOF
